Update protos

diff --git a/sdk-core-protos/protos/api_upstream/Makefile b/sdk-core-protos/protos/api_upstream/Makefile
--- a/sdk-core-protos/protos/api_upstream/Makefile
+++ b/sdk-core-protos/protos/api_upstream/Makefile
@@ -15,43 +15,54 @@ GOPATH := $(shell go env GOPATH)
 endif
 
 GOBIN := $(if $(shell go env GOBIN),$(shell go env GOBIN),$(GOPATH)/bin)
-SHELL := PATH=$(GOBIN):$(PATH) /bin/sh
+PATH := $(GOBIN):$(PATH)
+STAMPDIR := .stamp
 
 COLOR := "\e[1;36m%s\e[0m\n"
 
+# Only prints output if the exit code is non-zero
+define silent_exec
+    @output=$$($(1) 2>&1); \
+    status=$$?; \
+    if [ $$status -ne 0 ]; then \
+        echo "$$output"; \
+    fi; \
+    exit $$status
+endef
+
 PROTO_ROOT := .
-PROTO_FILES = $(shell find $(PROTO_ROOT) -name "*.proto")
+PROTO_FILES = $(shell find temporal -name "*.proto")
 PROTO_DIRS = $(sort $(dir $(PROTO_FILES)))
 PROTO_OUT := .gen
-PROTO_IMPORTS = -I=$(PROTO_ROOT) -I=$(shell go list -modfile build/go.mod -m -f '{{.Dir}}' github.com/temporalio/gogo-protobuf)/protobuf
+PROTO_IMPORTS = \
+	-I=$(PROTO_ROOT)
+PROTO_PATHS = paths=source_relative:$(PROTO_OUT)
 
 $(PROTO_OUT):
 	mkdir $(PROTO_OUT)
 
 ##### Compile proto files for go #####
-grpc: buf-lint api-linter buf-breaking gogo-grpc fix-path
+grpc: buf-lint api-linter buf-breaking clean go-grpc fix-path
 
 go-grpc: clean $(PROTO_OUT)
 	printf $(COLOR) "Compile for go-gRPC..."
-	$(foreach PROTO_DIR,$(PROTO_DIRS),protoc --fatal_warnings $(PROTO_IMPORTS) --go_out=plugins=grpc,paths=source_relative:$(PROTO_OUT) $(PROTO_DIR)*.proto;)
-
-gogo-grpc: clean $(PROTO_OUT)
-	printf $(COLOR) "Compile for gogo-gRPC..."
-	$(foreach PROTO_DIR,$(PROTO_DIRS),protoc --fatal_warnings $(PROTO_IMPORTS) --gogoslick_out=Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/wrappers.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/duration.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/descriptor.proto=github.com/golang/protobuf/protoc-gen-go/descriptor,Mgoogle/protobuf/timestamp.proto=github.com/gogo/protobuf/types,plugins=grpc,paths=source_relative:$(PROTO_OUT) $(PROTO_DIR)*.proto;)
+	$(foreach PROTO_DIR,$(PROTO_DIRS),\
+		protoc --fatal_warnings $(PROTO_IMPORTS) \
+		 	--go_out=$(PROTO_PATHS) \
+            --grpc-gateway_out=allow_patch_feature=false,$(PROTO_PATHS)\
+			--doc_out=html,index.html,source_relative:$(PROTO_OUT) \
+		$(PROTO_DIR)*.proto;)
 
 fix-path:
 	mv -f $(PROTO_OUT)/temporal/api/* $(PROTO_OUT) && rm -rf $(PROTO_OUT)/temporal
 
 ##### Plugins & tools #####
-grpc-install: gogo-protobuf-install
-	printf $(COLOR) "Install/update gRPC plugins..."
-	go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
-
-gogo-protobuf-install: go-protobuf-install
-	go install -modfile build/go.mod github.com/temporalio/gogo-protobuf/protoc-gen-gogoslick
-
-go-protobuf-install:
-	go install github.com/golang/protobuf/protoc-gen-go@v1.5.2
+grpc-install:
+	@printf $(COLOR) "Install/update protoc and plugins..."
+	@go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
+	@go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
+	@go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
+	@go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest
 
 api-linter-install:
 	printf $(COLOR) "Install/update api-linter..."
@@ -59,14 +70,22 @@ api-linter-install:
 
 buf-install:
 	printf $(COLOR) "Install/update buf..."
-	go install github.com/bufbuild/buf/cmd/buf@v1.6.0
+	go install github.com/bufbuild/buf/cmd/buf@v1.27.0
 
 ##### Linters #####
 api-linter:
 	printf $(COLOR) "Run api-linter..."
-	api-linter --set-exit-status $(PROTO_IMPORTS) --config $(PROTO_ROOT)/api-linter.yaml $(PROTO_FILES)
+	$(call silent_exec, api-linter --set-exit-status $(PROTO_IMPORTS) --config $(PROTO_ROOT)/api-linter.yaml $(PROTO_FILES))
 
-buf-lint:
+$(STAMPDIR):
+	mkdir $@
+
+$(STAMPDIR)/buf-mod-prune: $(STAMPDIR) buf.yaml
+	printf $(COLOR) "Pruning buf module"
+	buf mod prune
+	touch $@
+
+buf-lint: $(STAMPDIR)/buf-mod-prune
 	printf $(COLOR) "Run buf linter..."
 	(cd $(PROTO_ROOT) && buf lint)
 
@@ -77,4 +96,4 @@ buf-breaking:
 ##### Clean #####
 clean:
 	printf $(COLOR) "Delete generated go files..."
-	rm -rf $(PROTO_OUT)
+	rm -rf $(PROTO_OUT) $(BUF_DEPS)
